import { useEffect, useMemo, useState } from 'react'
import { BarChart3, CalendarDays, ChevronLeft, ChevronRight, RefreshCw } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

type Row = { id: number; provider: string; model: string; purpose: string; input_tokens: number; output_tokens: number; total_tokens: number; estimated: number; total_cost: number; created_at: string }
type Report = { summary: { calls: number; input_tokens: number; output_tokens: number; total_tokens: number; total_cost: number }; by_purpose: Array<{ purpose: string; calls: number; total_tokens: number }>; series: Array<{ bucket: string; total_tokens: number }>; recent_total: number; recent: Row[] }
const PURPOSE: Record<string, string> = { assistant_lab_reply: '\u6a21\u62df HR \u56de\u590d', interview_question: 'AI \u9762\u8bd5\u51fa\u9898', interview_evaluation: 'AI \u9762\u8bd5\u8bc4\u4ef7', scoring: '\u5c97\u4f4d AI \u8bc4\u5206', greeting_review: '\u62db\u547c\u8bed\u590d\u6838', hr_monitor_reply: 'HR \u6d88\u606f\u56de\u590d', tailored_resume: '\u5b9a\u5236\u7b80\u5386\u751f\u6210', unspecified: '\u672a\u5206\u7c7b\u8c03\u7528' }
const T = { title: '\u0054\u006f\u006b\u0065\u006e \u6d88\u8017', desc: '\u67e5\u770b\u6a21\u578b\u8c03\u7528\u6b21\u6570\u3001Token \u7528\u91cf\u548c\u8d39\u7528\u4f30\u7b97\u3002', start: '\u5f00\u59cb\u65e5\u671f', end: '\u7ed3\u675f\u65e5\u671f', granularity: '\u7edf\u8ba1\u7c92\u5ea6', day: '\u6309\u5929', hour: '\u6309\u5c0f\u65f6', refresh: '\u5237\u65b0', current: '\u6309\u5c0f\u65f6\u65f6，16:00:00 \u4ee3\u8868 16:00 \u81f3 16:59', calls: '\u6a21\u578b\u8c03\u7528\u6b21\u6570', input: '\u8f93\u5165 Token', output: '\u8f93\u51fa Token', total: '\u603b Token', cost: '\u9884\u8ba1\u8d39\u7528', byPurpose: '\u6309\u529f\u80fd\u6d88\u8017', trend: '\u65f6\u95f4\u8d8b\u52bf', recent: '\u6700\u8fd1\u8c03\u7528\u660e\u7ec6', time: '\u65f6\u95f4', purpose: '\u529f\u80fd', model: '\u6a21\u578b', next: '\u4e0b\u4e00\u9875', prev: '\u4e0a\u4e00\u9875' }
const fmt = (value: number) => new Intl.NumberFormat('zh-CN').format(value || 0)
const dateText = (value: Date) => value.toISOString().slice(0, 10)
const timeText = (value: string) => value ? value.replace('T', ' ').slice(0, 19) : '-'

export default function AIUsagePage() {
  const now = new Date(); const [start, setStart] = useState(dateText(new Date(now.getTime() - 6 * 86400000))); const [end, setEnd] = useState(dateText(now)); const [granularity, setGranularity] = useState<'day' | 'hour'>('day'); const [page, setPage] = useState(0); const [data, setData] = useState<Report | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const params = useMemo(() => new URLSearchParams({ start: `${start} 00:00:00`, end: `${end} 23:59:59`, granularity, offset: String(page * 15), limit: '15' }), [start, end, granularity, page])
  const pages = Math.max(1, Math.ceil((data?.recent_total || 0) / 15))
  const load = async () => { setLoading(true); setError(''); try { const response = await fetch(`/api/ai-usage?${params}`); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Token usage load failed'); setData(result) } catch (e) { setError(e instanceof Error ? e.message : 'Token usage load failed') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [params.toString()]); useEffect(() => { setPage(0) }, [start, end, granularity])
  const summary = data?.summary
  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-black">{T.title}</h2><p className="mt-1 text-sm text-muted">{T.desc}</p></div><Button variant="secondary" onClick={() => void load()} disabled={loading}><RefreshCw className="mr-2 h-4 w-4" />{T.refresh}</Button></div>
    <Card><CardContent className="flex flex-wrap items-end gap-4 pt-5"><label className="text-sm font-bold"><span className="mb-2 flex items-center gap-2"><CalendarDays className="h-4 w-4" />{T.start}</span><input type="date" value={start} max={end} onChange={e => setStart(e.target.value)} className="rounded-xl border border-card-border bg-white p-2.5 font-normal" /></label><label className="text-sm font-bold"><span className="mb-2 flex items-center gap-2"><CalendarDays className="h-4 w-4" />{T.end}</span><input type="date" value={end} min={start} onChange={e => setEnd(e.target.value)} className="rounded-xl border border-card-border bg-white p-2.5 font-normal" /></label><label className="text-sm font-bold">{T.granularity}<select value={granularity} onChange={e => setGranularity(e.target.value as 'day' | 'hour')} className="mt-2 block rounded-xl border border-card-border bg-white p-2.5 font-normal"><option value="day">{T.day}</option><option value="hour">{T.hour}</option></select></label><span className="text-xs text-muted">{T.current}</span></CardContent></Card>
    {error && <div className="rounded-xl bg-red-50 p-4 text-sm text-danger">{error}</div>}
    <div className="grid gap-4 md:grid-cols-5">{[[T.calls, summary?.calls], [T.input, summary?.input_tokens], [T.output, summary?.output_tokens], [T.total, summary?.total_tokens], [T.cost, `¥${(summary?.total_cost || 0).toFixed(4)}`]].map(([label, value]) => <Card key={String(label)}><CardHeader><CardTitle className="text-sm text-muted">{label}</CardTitle></CardHeader><CardContent><div className="text-2xl font-black">{typeof value === 'number' ? fmt(value) : value || '0'}</div></CardContent></Card>)}</div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-indigo-600" />{T.byPurpose}</CardTitle></CardHeader><CardContent className="space-y-3">{data?.by_purpose.length ? data.by_purpose.map(item => <div key={item.purpose} className="flex justify-between text-sm"><span>{PURPOSE[item.purpose] || item.purpose}</span><b>{fmt(item.total_tokens)} Token · {item.calls} 次</b></div>) : <span className="text-sm text-muted">当前范围暂无记录</span>}</CardContent></Card><Card><CardHeader><CardTitle>{T.trend}（{granularity === 'hour' ? T.hour : T.day}）</CardTitle></CardHeader><CardContent className="space-y-2">{data?.series.length ? data.series.map(item => <div key={item.bucket} className="flex justify-between text-sm"><span>{item.bucket}</span><b>{fmt(item.total_tokens)} Token</b></div>) : <span className="text-sm text-muted">当前范围暂无记录</span>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>{T.recent}（共 {data?.recent_total || 0} 条，每页 15 条，最新在前）</CardTitle></CardHeader><CardContent>{loading ? <div className="text-sm text-muted">Loading...</div> : <><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted"><th className="p-3">{T.time}</th><th className="p-3">{T.purpose}</th><th className="p-3">{T.model}</th><th className="p-3">{T.input}</th><th className="p-3">{T.output}</th><th className="p-3">{T.total}</th><th className="p-3">{T.cost}</th></tr></thead><tbody>{data?.recent.map(item => <tr key={item.id} className="border-b last:border-0"><td className="p-3 whitespace-nowrap">{timeText(item.created_at)}</td><td className="p-3">{PURPOSE[item.purpose] || item.purpose}</td><td className="p-3">{item.model || item.provider || '-'}</td><td className="p-3">{fmt(item.input_tokens)}</td><td className="p-3">{fmt(item.output_tokens)}</td><td className="p-3 font-bold">{fmt(item.total_tokens)}{item.estimated ? '（估算）' : ''}</td><td className="p-3">¥{(item.total_cost || 0).toFixed(4)}</td></tr>)}</tbody></table></div>{!data?.recent.length && <div className="py-8 text-center text-sm text-muted">当前范围暂无调用明细</div>}<div className="mt-4 flex items-center justify-between text-sm"><span>第 {Math.min(page + 1, pages)} / {pages} 页</span><div className="flex gap-2"><Button variant="secondary" size="sm" disabled={page === 0 || loading} onClick={() => setPage(value => value - 1)}><ChevronLeft className="h-4 w-4" />{T.prev}</Button><Button variant="secondary" size="sm" disabled={page + 1 >= pages || loading} onClick={() => setPage(value => value + 1)}>{T.next}<ChevronRight className="h-4 w-4" /></Button></div></div></>}</CardContent></Card>
  </div>
}
