import { useEffect, useRef, useState } from 'react'
import { AudioLines, Bot, Mic, MicOff, Volume2, VolumeX } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

interface RecognitionResultEvent extends Event { results: SpeechRecognitionResultList; resultIndex: number }
interface RecognitionErrorEvent extends Event { error: string }
interface RecognitionLike { continuous: boolean; interimResults: boolean; lang: string; onresult: ((event: RecognitionResultEvent) => void) | null; onerror: ((event: RecognitionErrorEvent) => void) | null; onend: (() => void) | null; start: () => void; stop: () => void; abort: () => void }
interface RecognitionConstructor { new (): RecognitionLike }
interface SpeechWindow extends Window { SpeechRecognition?: RecognitionConstructor; webkitSpeechRecognition?: RecognitionConstructor }

const SILENCE_KEY = 'ajh.voice.silenceSeconds'
const THRESHOLD_KEY = 'ajh.voice.volumeThreshold'
const AUTO_SPEAK_KEY = 'ajh.voice.autoSpeak'
const VOLUME_KEY = 'ajh.voice.volume'

export default function VoiceAssistantPage() {
  const [status, setStatus] = useState<'idle' | 'listening' | 'processing' | 'speaking'>('idle')
  const [transcript, setTranscript] = useState('')
  const [interim, setInterim] = useState('')
  const [reply, setReply] = useState('')
  const [level, setLevel] = useState(0)
  const [notice, setNotice] = useState('')
  const [silenceSeconds, setSilenceSeconds] = useState(() => Number(localStorage.getItem(SILENCE_KEY) || 5))
  const [threshold, setThreshold] = useState(() => Number(localStorage.getItem(THRESHOLD_KEY) || 0.02))
  const [autoSpeak, setAutoSpeak] = useState(() => localStorage.getItem(AUTO_SPEAK_KEY) !== 'false')
  const [volume, setVolume] = useState(() => Number(localStorage.getItem(VOLUME_KEY) || 0.9))
  const recognitionRef = useRef<RecognitionLike | null>(null); const streamRef = useRef<MediaStream | null>(null); const audioContextRef = useRef<AudioContext | null>(null); const analyserRef = useRef<AnalyserNode | null>(null); const rafRef = useRef<number | null>(null); const finalTextRef = useRef(''); const listeningRef = useRef(false); const lastLoudRef = useRef(0); const heardVoiceRef = useRef(false); const finishingRef = useRef(false)

  useEffect(() => () => { stopCapture(); window.speechSynthesis.cancel() }, [])
  const persist = (key: string, value: string) => localStorage.setItem(key, value)
  const stopCapture = () => { listeningRef.current = false; if (rafRef.current) cancelAnimationFrame(rafRef.current); rafRef.current = null; recognitionRef.current?.abort(); recognitionRef.current = null; streamRef.current?.getTracks().forEach(track => track.stop()); streamRef.current = null; if (audioContextRef.current && audioContextRef.current.state !== 'closed') void audioContextRef.current.close(); audioContextRef.current = null; analyserRef.current = null; setLevel(0) }
  const speak = (text: string) => { if (!text || !autoSpeak) return; window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = 'zh-CN'; utterance.volume = volume; utterance.rate = 1; utterance.onstart = () => setStatus('speaking'); utterance.onend = () => setStatus('idle'); window.speechSynthesis.speak(utterance) }
  const askAI = async (question: string) => { setStatus('processing'); try { const response = await fetch('/api/voice-assistant/reply', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'AI 回复失败'); setReply(data.reply || '暂时没有生成回复'); setNotice(data.generation_mode === 'configured_model' ? '已结合个人资料生成回复' : '当前使用本地兜底回复，请检查 AI 配置'); speak(data.reply || '') } catch (error) { setNotice(error instanceof Error ? error.message : 'AI 回复失败'); setStatus('idle') } }
  const finish = () => { if (finishingRef.current) return; finishingRef.current = true; const question = finalTextRef.current.trim(); stopCapture(); if (!question) { setStatus('idle'); setNotice('没有识别到有效问题，请重新点击麦克风'); finishingRef.current = false; return } setTranscript(question); setInterim(''); void askAI(question).finally(() => { finishingRef.current = false }) }
  const drawLevel = () => { const analyser = analyserRef.current; if (!analyser || !listeningRef.current) return; const values = new Uint8Array(analyser.fftSize); analyser.getByteTimeDomainData(values); let sum = 0; for (const value of values) { const normalized = (value - 128) / 128; sum += normalized * normalized } const rms = Math.sqrt(sum / values.length); setLevel(Math.min(1, rms * 8)); if (rms > threshold) { lastLoudRef.current = Date.now(); heardVoiceRef.current = true } else if (heardVoiceRef.current && Date.now() - lastLoudRef.current >= silenceSeconds * 1000) { finish(); return } rafRef.current = requestAnimationFrame(drawLevel) }
  const start = async () => { const SpeechRecognition = (window as SpeechWindow).SpeechRecognition || (window as SpeechWindow).webkitSpeechRecognition; if (!SpeechRecognition) { setNotice('当前浏览器不支持语音识别，请使用最新版 Chrome，或直接输入文字'); return } try { setNotice('正在申请麦克风权限...'); const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); streamRef.current = stream; const context = new AudioContext(); const analyser = context.createAnalyser(); analyser.fftSize = 512; context.createMediaStreamSource(stream).connect(analyser); audioContextRef.current = context; analyserRef.current = analyser; finalTextRef.current = ''; heardVoiceRef.current = false; lastLoudRef.current = Date.now(); finishingRef.current = false; const recognition = new SpeechRecognition(); recognition.continuous = true; recognition.interimResults = true; recognition.lang = 'zh-CN'; recognition.onresult = event => { let partial = ''; let final = finalTextRef.current; for (let index = event.resultIndex; index < event.results.length; index += 1) { const result = event.results[index]; if (result.isFinal) final += result[0].transcript; else partial += result[0].transcript } finalTextRef.current = final; setTranscript(final); setInterim(partial) }; recognition.onerror = event => { if (event.error !== 'aborted' && event.error !== 'no-speech') setNotice(`语音识别提示：${event.error}`) }; recognition.onend = () => { if (listeningRef.current && !finishingRef.current) { try { recognition.start() } catch { /* browser may already be restarting */ } } }; recognitionRef.current = recognition; listeningRef.current = true; setStatus('listening'); setNotice(`正在监听，连续 ${silenceSeconds} 秒低于阈值将自动提交`); recognition.start(); rafRef.current = requestAnimationFrame(drawLevel) } catch (error) { stopCapture(); setStatus('idle'); setNotice(error instanceof Error ? error.message : '无法访问麦克风，请检查浏览器权限') } }
  const submitManually = () => { const question = `${transcript}${interim}`.trim(); if (!question || status === 'processing') return; finalTextRef.current = question; stopCapture(); setTranscript(question); setInterim(''); void askAI(question) }
  const stop = () => { if (status === 'listening') finish(); else stopCapture() }
  return <div className="space-y-5"><div className="rounded-3xl border border-indigo-100 bg-indigo-50/60 p-5"><div className="flex items-start gap-3"><div className="rounded-2xl bg-indigo-600 p-3 text-white"><AudioLines className="h-5 w-5" /></div><div><h2 className="text-xl font-black">语音求职助手</h2><p className="mt-1 text-sm text-muted">浏览器实时转写 HR 问题，结合个人简历和知识库生成求职者口吻回复。</p></div></div><p className="mt-4 rounded-2xl border border-indigo-200 bg-white px-3 py-2 text-xs text-indigo-700">本功能不保存原始音频，不打开 Chrome 自动化页面，不请求 BOSS。</p></div>
    <div className="grid gap-4 lg:grid-cols-[280px_1fr]"><Card><CardHeader><CardTitle>监听设置</CardTitle></CardHeader><CardContent className="space-y-4"><label className="block text-sm font-bold">静音结束时间：{silenceSeconds} 秒<input type="range" min="1" max="15" step="1" value={silenceSeconds} onChange={e => { const value = Number(e.target.value); setSilenceSeconds(value); persist(SILENCE_KEY, String(value)) }} className="mt-2 w-full" /></label><label className="block text-sm font-bold">音量阈值：{threshold.toFixed(3)}<input type="range" min="0.005" max="0.1" step="0.005" value={threshold} onChange={e => { const value = Number(e.target.value); setThreshold(value); persist(THRESHOLD_KEY, String(value)) }} className="mt-2 w-full" /></label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={autoSpeak} onChange={e => { setAutoSpeak(e.target.checked); persist(AUTO_SPEAK_KEY, String(e.target.checked)) }} />自动朗读 AI 回复</label><label className="block text-sm font-bold">朗读音量：{Math.round(volume * 100)}%<input type="range" min="0" max="1" step="0.05" value={volume} onChange={e => { const value = Number(e.target.value); setVolume(value); persist(VOLUME_KEY, String(value)) }} className="mt-2 w-full" /></label></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Mic className="h-5 w-5 text-indigo-600" />{status === 'listening' ? '正在监听' : status === 'processing' ? '正在生成回复' : status === 'speaking' ? '正在朗读' : '点击开始提问'}</CardTitle></CardHeader><CardContent><div className="flex flex-col items-center"><button type="button" onClick={() => status === 'listening' ? stop() : void start()} className={`flex h-32 w-32 items-center justify-center rounded-full text-white shadow-xl transition ${status === 'listening' ? 'bg-red-500 ring-8 ring-red-100' : 'bg-indigo-600 hover:bg-indigo-700'}`}>{status === 'listening' ? <MicOff className="h-12 w-12" /> : <Mic className="h-12 w-12" />}</button><div className="mt-5 h-3 w-full max-w-md overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500 transition-all" style={{ width: `${Math.round(level * 100)}%` }} /></div><div className="mt-3 flex gap-2"><Button variant="secondary" onClick={submitManually} disabled={status === 'processing' || !`${transcript}${interim}`.trim()}>立即提交</Button><Button variant="secondary" onClick={() => { window.speechSynthesis.cancel(); setStatus('idle') }}><VolumeX className="mr-2 h-4 w-4" />停止朗读</Button></div></div></CardContent></Card></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>实时识别文字</CardTitle></CardHeader><CardContent><div className="min-h-36 rounded-2xl bg-[#FFFCFA] p-5 text-2xl font-bold leading-relaxed">{transcript || <span className="text-base font-normal text-muted">点击麦克风后，对着电脑说出 HR 的问题...</span>}<span className="text-indigo-500">{interim}</span></div><textarea aria-label="文字降级输入" value={transcript} onChange={event => { setTranscript(event.target.value); finalTextRef.current = event.target.value }} placeholder="浏览器不支持语音识别时，也可以直接输入问题" className="mt-3 min-h-20 w-full rounded-2xl border border-card-border p-3 text-sm" /></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Bot className="h-5 w-5 text-emerald-600" />AI 回复</CardTitle></CardHeader><CardContent><div className="min-h-36 rounded-2xl bg-emerald-50 p-5 text-xl leading-relaxed">{reply || <span className="text-base text-muted">识别结束后，AI 回复会显示在这里。</span>}</div>{reply && autoSpeak && <p className="mt-3 flex items-center gap-2 text-xs text-muted"><Volume2 className="h-4 w-4" />已按当前音量自动朗读</p>}</CardContent></Card></div>{notice && <p className="text-sm text-emerald-700">{notice}</p>}</div>
}
